package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/semenov/ship/internal/detect"
	"github.com/semenov/ship/internal/proto"
)

func ejectCmd() *cobra.Command {
	var force bool
	c := &cobra.Command{
		Use:   "eject [dir]",
		Short: "Write the generated Dockerfile and .dockerignore into the project to customize them",
		Long: `Without a Dockerfile, ship generates one for the detected stack. eject writes
that Dockerfile (and a matching .dockerignore, unless the project has one) into
the project. From then on ship builds from your files, so you can change them;
improvements to ship's generated Dockerfiles no longer apply to this project.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := "."
			if len(args) == 1 {
				dir = args[0]
			}
			proj, _, err := loadProject(dir)
			if err != nil {
				return err
			}
			plan, err := detect.Detect(dir, proj.Dockerfile, proj.Start)
			if err != nil {
				return err
			}
			if plan.Generated == "" {
				return proto.Errf(proto.CodeConfig, "", "the project already builds from %s; nothing to eject", plan.Dockerfile)
			}
			df := filepath.Join(dir, "Dockerfile")
			if _, err := os.Stat(df); err == nil && !force {
				return proto.Errf(proto.CodeConfig, "use --force to overwrite", "%s already exists", df)
			}
			header := fmt.Sprintf("# Generated by `ship eject` for a %s project. ship now builds from this file;\n# edit it freely. The app must listen on 0.0.0.0:$PORT (PORT=%d).\n\n", plan.Stack, plan.Port)
			if err := os.WriteFile(df, []byte(header+plan.Generated), 0o644); err != nil {
				return err
			}
			res := map[string]any{"dockerfile": df, "stack": plan.Stack, "port": plan.Port}
			ignore := filepath.Join(dir, ".dockerignore")
			if _, err := os.Stat(ignore); err == nil {
				res["dockerignore_kept"] = ignore
			} else {
				if err := os.WriteFile(ignore, []byte(plan.Ignore), 0o644); err != nil {
					return err
				}
				res["dockerignore"] = ignore
			}
			emit(res, func() {
				fmt.Printf("✓ wrote %s (%s, port %d)\n", df, plan.Stack, plan.Port)
				if p, ok := res["dockerignore"]; ok {
					fmt.Printf("✓ wrote %s\n", p)
				} else {
					fmt.Printf("  kept the existing %s\n", ignore)
				}
				fmt.Println("  ship now builds from these files; commit them")
			})
			return nil
		},
	}
	c.Flags().BoolVar(&force, "force", false, "overwrite an existing Dockerfile")
	return c
}
