package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/semenov/homebase/internal/config"
	"github.com/semenov/homebase/internal/detect"
	"github.com/semenov/homebase/internal/proto"
)

func ejectCmd() *cobra.Command {
	var force bool
	c := &cobra.Command{
		Use:   "eject [dir]",
		Short: "Write the Dockerfile that deploys use into the project, to customize it",
		Long: `Without a Dockerfile, homebase generates one for the detected stack when it
deploys. eject writes that Dockerfile (and a matching .dockerignore, unless the
project has one) into the project. From then on deploys build from your files, so
you can change them; improvements to homebase's generated Dockerfiles no longer
apply to this project.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := loadConfig()
			if err != nil {
				return err
			}
			dir, err := projectDir(cfg, firstArg(args))
			if err != nil {
				return err
			}
			proj, err := config.LoadProject(dir)
			if err != nil {
				return errf(CodeConfig, "fix the file and try again", "%v", err)
			}
			d := &config.Deploy{}
			if proj != nil && proj.Deploy != nil {
				d = proj.Deploy
			}
			plan, err := detect.Build(dir, d.Dockerfile, d.Start)
			if err != nil {
				return err
			}
			if plan.Generated == "" {
				return proto.Errf(proto.CodeConfig, "", "the project already builds from %s; nothing to eject", plan.Dockerfile)
			}
			df := filepath.Join(dir, "Dockerfile")
			if _, err := os.Stat(df); err == nil && !force {
				return proto.Errf(proto.CodeConfig, "use --force to overwrite", "%s already exists", df)
			}
			header := fmt.Sprintf("# Generated by `homebase eject` for a %s project. `homebase deploy` now builds\n# from this file; edit it freely. The app must listen on 0.0.0.0:$PORT (PORT=%d).\n\n", plan.Stack, plan.Port)
			if err := os.WriteFile(df, []byte(header+plan.Generated), 0o644); err != nil {
				return err
			}
			res := map[string]any{"dockerfile": df, "stack": plan.Stack, "port": plan.Port}
			ignore := filepath.Join(dir, ".dockerignore")
			if _, err := os.Stat(ignore); err == nil {
				res["dockerignore_kept"] = ignore
			} else {
				if err := os.WriteFile(ignore, []byte(plan.Ignore), 0o644); err != nil {
					return err
				}
				res["dockerignore"] = ignore
			}
			emit(res, func(u *UI) {
				u.OK("Wrote the Dockerfile")
				u.KV("Dockerfile", short(df)+u.p.dim(fmt.Sprintf(" (%s, port %d)", plan.Stack, plan.Port)))
				if p, ok := res["dockerignore"]; ok {
					u.KV("Ignore", short(fmt.Sprint(p)))
				} else {
					u.KV("Ignore", short(ignore)+u.p.dim(" (kept)"))
				}
				u.Para("homebase deploy builds from these files from now on. Commit them.")
			})
			return nil
		},
	}
	c.Flags().BoolVar(&force, "force", false, "overwrite an existing Dockerfile")
	return c
}
