// Package cloudflared wraps the cloudflared CLI for a locally-managed
// Cloudflare Tunnel: credentials and the origin cert live in ~/.cloudflared.
package cloudflared

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func dir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".cloudflared")
}

// Path returns the cloudflared binary, or an install hint.
func Path() (string, error) {
	p, err := exec.LookPath("cloudflared")
	if err != nil {
		return "", errors.New("cloudflared is not installed — brew install cloudflared")
	}
	return p, nil
}

// LoggedIn reports whether `cloudflared tunnel login` has been run.
func LoggedIn() bool {
	cert := os.Getenv("TUNNEL_ORIGIN_CERT")
	if cert == "" {
		cert = filepath.Join(dir(), "cert.pem")
	}
	_, err := os.Stat(cert)
	return err == nil
}

func CredentialsPath(id string) string { return filepath.Join(dir(), id+".json") }

func run(args ...string) (string, error) {
	bin, err := Path()
	if err != nil {
		return "", err
	}
	out, err := exec.Command(bin, args...).CombinedOutput()
	if err != nil {
		return string(out), fmt.Errorf("cloudflared %s: %s", strings.Join(args, " "), strings.TrimSpace(string(out)))
	}
	return string(out), nil
}

// FindTunnel returns the ID of the tunnel with this name, or "" if none.
func FindTunnel(name string) (string, error) {
	bin, err := Path()
	if err != nil {
		return "", err
	}
	// stdout only: cloudflared logs to stderr.
	out, err := exec.Command(bin, "tunnel", "list", "--output", "json", "--name", name).Output()
	if err != nil {
		return "", fmt.Errorf("cloudflared tunnel list: %w", err)
	}
	var tunnels []struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	}
	if s := strings.TrimSpace(string(out)); s != "" && s != "null" {
		if err := json.Unmarshal([]byte(s), &tunnels); err != nil {
			return "", fmt.Errorf("parse tunnel list: %w", err)
		}
	}
	for _, t := range tunnels {
		if t.Name == name {
			return t.ID, nil
		}
	}
	return "", nil
}

// EnsureTunnel returns the ID of the named tunnel, creating it if needed.
func EnsureTunnel(name string) (string, error) {
	id, err := FindTunnel(name)
	if err != nil || id != "" {
		return id, err
	}
	if _, err := run("tunnel", "create", name); err != nil {
		return "", err
	}
	id, err = FindTunnel(name)
	if err == nil && id == "" {
		err = fmt.Errorf("tunnel %q was created but does not show up in `cloudflared tunnel list`", name)
	}
	return id, err
}

// RouteDNS points host at the tunnel with a proxied CNAME record. It is a
// no-op if the record already routes to this tunnel, and fails if the
// hostname is taken by another record.
func RouteDNS(tunnelID, host string) error {
	_, err := run("tunnel", "route", "dns", tunnelID, host)
	return err
}

// WriteConfig writes a cloudflared config that sends every hostname of the
// tunnel to the homebase proxy's tunnel listener.
func WriteConfig(path, tunnelID string, port int) error {
	cfg := fmt.Sprintf(`# Generated by homebase. Every hostname routed to this tunnel goes to the
# homebase proxy, which decides which server (if any) is shared.
tunnel: %s
credentials-file: %s
ingress:
  - service: http://127.0.0.1:%d
`, tunnelID, CredentialsPath(tunnelID), port)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(cfg), 0o644)
}
